package dentistrymanager.gui;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ScrollPaneConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class FindPatient extends JFrame {

    /**
     * Creates new form FindPatient
     */
    public FindPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //GEN-BEGIN:initComponents
    private void initComponents() {

        printReceipt = new JDialog();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        printRecieptPayButton = new JButton();
        printRecieptCloseButton = new JButton();
        changePlan = new JDialog();
        planComboBox = new JComboBox<>();
        updatePlan = new JButton();
        planClosebutton = new JButton();
        SearchField = new JTextField();
        SearchButton = new JButton();
        searchResults = new JScrollPane();
        searchResultsList = new JList<>();
        patientDetails = new JPanel();
        nameLabel = new JLabel();
        nameField = new JTextField();
        addressLabel = new JLabel();
        addressField = new JScrollPane();
        addressArea = new JTextArea();
        phoneLabel = new JLabel();
        phoneField = new JTextField();
        healthcareLabel = new JLabel();
        healthCarePanel = new JPanel();
        planNameArea = new JTextField();
        subscribeButton = new JButton();
        owedLabel = new JLabel();
        jPanel1 = new JPanel();
        owedField = new JTextField();
        receiptButton = new JButton();
        deleteButton = new JButton();

        printReceipt.setAlwaysOnTop(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        printRecieptPayButton.setText("Pay All");
        printRecieptPayButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                printRecieptPayButtonActionPerformed(evt);
            }
        });

        printRecieptCloseButton.setText("Close");

        GroupLayout printReceiptLayout = new GroupLayout(printReceipt.getContentPane());
        printReceipt.getContentPane().setLayout(printReceiptLayout);
        printReceiptLayout.setHorizontalGroup(
            printReceiptLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(printReceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(printReceiptLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(printReceiptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printRecieptPayButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printRecieptCloseButton)))
                .addContainerGap())
        );
        printReceiptLayout.setVerticalGroup(
            printReceiptLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(printReceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printReceiptLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(printRecieptPayButton)
                    .addComponent(printRecieptCloseButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        planComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updatePlan.setText("Update Plan");

        planClosebutton.setText("Close");

        GroupLayout changePlanLayout = new GroupLayout(changePlan.getContentPane());
        changePlan.getContentPane().setLayout(changePlanLayout);
        changePlanLayout.setHorizontalGroup(
            changePlanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(changePlanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePlanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(planComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(changePlanLayout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(updatePlan)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(planClosebutton)))
                .addContainerGap())
        );
        changePlanLayout.setVerticalGroup(
            changePlanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(changePlanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePlanLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePlan)
                    .addComponent(planClosebutton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(600, 400));
        setPreferredSize(new Dimension(600, 400));
        setResizable(true);

        SearchField.setText("Search");

        SearchButton.setText("Search");

        searchResultsList.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        searchResults.setViewportView(searchResultsList);

        patientDetails.setBorder(BorderFactory.createEtchedBorder());
        patientDetails.setToolTipText(" details");
        patientDetails.setName(""); // NOI18N

        nameLabel.setText("Name:");

        nameField.setEditable(false);
        nameField.setText("jTextField1");

        addressLabel.setText("Address:");

        addressField.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        addressField.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        addressField.setMinimumSize(new Dimension(12, 12));

        addressArea.setColumns(20);
        addressArea.setRows(5);
        addressField.setViewportView(addressArea);

        phoneLabel.setText("Phone number:");

        phoneField.setText("jTextField2");

        healthcareLabel.setText("Healthcare plan:");

        healthCarePanel.setBorder(BorderFactory.createEtchedBorder());

        planNameArea.setText("Name of plan");

        subscribeButton.setText("Subscribe");

        GroupLayout healthCarePanelLayout = new GroupLayout(healthCarePanel);
        healthCarePanel.setLayout(healthCarePanelLayout);
        healthCarePanelLayout.setHorizontalGroup(
            healthCarePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(healthCarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(healthCarePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(planNameArea, GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, healthCarePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(subscribeButton)))
                .addContainerGap())
        );
        healthCarePanelLayout.setVerticalGroup(
            healthCarePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(healthCarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planNameArea, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subscribeButton)
                .addContainerGap())
        );

        owedLabel.setText("Owed:");

        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        owedField.setText("jTextField4");

        receiptButton.setText("Receipt");
        receiptButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                receiptButtonActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(owedField, GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(receiptButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(owedField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiptButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        deleteButton.setText("Delete Patient");

        GroupLayout patientDetailsLayout = new GroupLayout(patientDetails);
        patientDetailsLayout.setHorizontalGroup(
        	patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(patientDetailsLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(deleteButton, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        				.addGroup(patientDetailsLayout.createSequentialGroup()
        					.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(patientDetailsLayout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(patientDetailsLayout.createSequentialGroup()
        								.addComponent(nameLabel)
        								.addGap(24))
        							.addGroup(patientDetailsLayout.createSequentialGroup()
        								.addComponent(phoneLabel)
        								.addGap(18)))
        						.addComponent(addressLabel))
        					.addGap(32)
        					.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(addressField, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        						.addComponent(nameField, 301, 301, 301)
        						.addComponent(phoneField, 301, 301, 301)))
        				.addGroup(patientDetailsLayout.createSequentialGroup()
        					.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(healthcareLabel)
        						.addComponent(owedLabel))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        						.addComponent(healthCarePanel, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        patientDetailsLayout.setVerticalGroup(
        	patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(patientDetailsLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(nameLabel)
        				.addComponent(nameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(phoneField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(phoneLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(addressLabel, Alignment.LEADING)
        				.addComponent(addressField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(healthcareLabel)
        				.addComponent(healthCarePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(patientDetailsLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(owedLabel)
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE))
        			.addGap(18)
        			.addComponent(deleteButton)
        			.addContainerGap())
        );
        patientDetails.setLayout(patientDetailsLayout);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchField, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchResults, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientDetails, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(searchResults)
                    .addComponent(patientDetails, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void receiptButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void printRecieptPayButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(RegisterPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RegisterPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RegisterPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JButton SearchButton;
    private JTextField SearchField;
    private JTextArea addressArea;
    private JScrollPane addressField;
    private JLabel addressLabel;
    private JDialog changePlan;
    private JButton deleteButton;
    private JPanel healthCarePanel;
    private JLabel healthcareLabel;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private JTextField nameField;
    private JLabel nameLabel;
    private JTextField owedField;
    private JLabel owedLabel;
    private JPanel patientDetails;
    private JTextField phoneField;
    private JLabel phoneLabel;
    private JButton planClosebutton;
    private JComboBox<String> planComboBox;
    private JTextField planNameArea;
    private JDialog printReceipt;
    private JButton printRecieptCloseButton;
    private JButton printRecieptPayButton;
    private JButton receiptButton;
    private JScrollPane searchResults;
    private JList<String> searchResultsList;
    private JButton subscribeButton;
    private JButton updatePlan;
    // End of variables declaration
}
