/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistrymanager.gui;

/**
 *
 * @author joe
 */
public class SecretaryCalendar extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryCalendar
     */
    public SecretaryCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secretaryCalendarTabPane = new javax.swing.JTabbedPane();
        dentistTabPanel = new javax.swing.JPanel();
        dentistCalendarListPane = new javax.swing.JScrollPane();
        dentistCalendarList = new javax.swing.JList<>();
        dentistAddAppButton = new javax.swing.JButton();
        dentistDeleteAppButton = new javax.swing.JButton();
        hygienistTabPanel = new javax.swing.JPanel();
        hygienistCalendarListPane = new javax.swing.JScrollPane();
        hygienistCalendarList = new javax.swing.JList<>();
        hygienistAddAppButton = new javax.swing.JButton();
        hygienistDeleteAppButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dentistCalendarList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        dentistCalendarListPane.setViewportView(dentistCalendarList);

        dentistAddAppButton.setText("Add appointment");

        dentistDeleteAppButton.setText("Delete appointment");

        javax.swing.GroupLayout dentistTabPanelLayout = new javax.swing.GroupLayout(dentistTabPanel);
        dentistTabPanel.setLayout(dentistTabPanelLayout);
        dentistTabPanelLayout.setHorizontalGroup(
            dentistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dentistTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dentistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dentistCalendarListPane)
                    .addGroup(dentistTabPanelLayout.createSequentialGroup()
                        .addComponent(dentistAddAppButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dentistDeleteAppButton)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dentistTabPanelLayout.setVerticalGroup(
            dentistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dentistTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dentistCalendarListPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dentistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dentistAddAppButton)
                    .addComponent(dentistDeleteAppButton))
                .addContainerGap())
        );

        secretaryCalendarTabPane.addTab("Dentist", dentistTabPanel);

        hygienistCalendarList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        hygienistCalendarListPane.setViewportView(hygienistCalendarList);

        hygienistAddAppButton.setText("Add appointment");

        hygienistDeleteAppButton.setText("Delete appointment");

        javax.swing.GroupLayout hygienistTabPanelLayout = new javax.swing.GroupLayout(hygienistTabPanel);
        hygienistTabPanel.setLayout(hygienistTabPanelLayout);
        hygienistTabPanelLayout.setHorizontalGroup(
            hygienistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hygienistTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hygienistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hygienistCalendarListPane)
                    .addGroup(hygienistTabPanelLayout.createSequentialGroup()
                        .addComponent(hygienistAddAppButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hygienistDeleteAppButton)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        hygienistTabPanelLayout.setVerticalGroup(
            hygienistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hygienistTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hygienistCalendarListPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hygienistTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hygienistAddAppButton)
                    .addComponent(hygienistDeleteAppButton))
                .addContainerGap())
        );

        secretaryCalendarTabPane.addTab("Hygienist", hygienistTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secretaryCalendarTabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secretaryCalendarTabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dentistAddAppButton;
    private javax.swing.JList<String> dentistCalendarList;
    private javax.swing.JScrollPane dentistCalendarListPane;
    private javax.swing.JButton dentistDeleteAppButton;
    private javax.swing.JPanel dentistTabPanel;
    private javax.swing.JButton hygienistAddAppButton;
    private javax.swing.JList<String> hygienistCalendarList;
    private javax.swing.JScrollPane hygienistCalendarListPane;
    private javax.swing.JButton hygienistDeleteAppButton;
    private javax.swing.JPanel hygienistTabPanel;
    private javax.swing.JTabbedPane secretaryCalendarTabPane;
    // End of variables declaration//GEN-END:variables
}
