package dentistrymanager.gui;

import java.awt.Dimension;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class SplashScreen extends JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new JPanel();
        SecretaryButton = new JButton();
        DentistButton = new JButton();
        HygienistButton = new JButton();

        SecretaryButton.setText("Secretary");
        DentistButton.setText("Dentist");
        HygienistButton.setText("Hygienist");

        GroupLayout buttonPanelLayout = new GroupLayout(buttonPanel);
        buttonPanelLayout.setHorizontalGroup(
        	buttonPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(buttonPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(SecretaryButton, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(DentistButton, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(HygienistButton, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        			.addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
        	buttonPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(buttonPanelLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(DentistButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        				.addComponent(SecretaryButton, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        				.addComponent(HygienistButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        			.addContainerGap())
        );
        buttonPanel.setLayout(buttonPanelLayout);

        GroupLayout layout = new GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(buttonPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(90)
        			.addComponent(buttonPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(92, Short.MAX_VALUE))
        );
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(600, 400));
        setPreferredSize(new Dimension(600, 400));
        setResizable(true);
        
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify
    private JButton DentistButton;
    private JButton HygienistButton;
    private JButton SecretaryButton;
    private JPanel buttonPanel;
    // End of variables declaration
}
